# docker-compose.yml

version: '3.10'
services:
  flask:
    image: flask
#    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./flaskapp:/app
    environment:
      - FLASK_ENV=development
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=projectdb447
      - MYSQL_USER=projectuser
      - MYSQL_PASSWORD=changeme
    ports:
      - "3306:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
volumes:
  es_data:
